version: '3.8'
# docker-compose -f docker-compose-app-v1.0.yml up -d
services:
  ai-mcp-knowledge-app:
    image: registry.cn-hangzhou.aliyuncs.com/qx-images/ai-mcp-knowledge-app:1.1
    #image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/ai-mcp-knowledge-app:1.0
    container_name: ai-mcp-knowledge-app
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./log:/data/log
      - ./mcp/config:/mcp/config
      - ./mcp/jar:/mcp/jar
    environment:
      - TZ=PRC
      - SERVER_PORT=8090
      - SPRING_AI_OLLAMA_BASE_URL=http://58a39caa684c41bf9bed-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      - SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_NUM_BATCH=512
      - SPRING_AI_OLLAMA_MODEL=nomic-embed-text
      - SPRING_AI_OPENAI_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode
      - SPRING_AI_OPENAI_API_KEY=sk-87d49e5a3e2946288df86c0466613e0c
      # - SPRING_AI_MCP_CLIENT_STDIO_SERVERS_CONFIGURATION=file:/mcp/config/mcp-servers-config.json
      - SPRING_AI_MCP_CLIENT_REQUEST_TIMEOUT=360s
      - SPRING_AI_MCP_CLIENT_SSE_CONNECTIONS_MCP_SERVER_CSDN_URL=http://mcp-server-csdn-app:8101
      - SPRING_AI_MCP_CLIENT_SSE_CONNECTIONS_MCP_SERVER_WEIXIN_URL=http://mcp-server-weixin-app:8102

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mcp-server-csdn-app
      - mcp-server-weixin-app
    networks:
      - my-network

  mcp-server-csdn-app:
    #    image: fuzhengwei/mcp-server-csdn-app:1.1
    image: registry.cn-hangzhou.aliyuncs.com/qx-images/mcp-server-csdn-app:1.0
    container_name: mcp-server-csdn-app
    restart: always
    ports:
      - "8101:8101"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=8101
      - CSDN_API_CATEGORIES=Java场景面试宝典
      - CSDN_API_COOKIE=uuid_tt_dd=10_37073317040-1744940142681-439048; fid=20_84371068999-1744940143833-824314; c_segment=8; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=1744940145,1744947444; HMACCOUNT=8F2656BD4C17EE58; dc_sid=51b07b8730c50fd4413a1975b125674a; loginbox_strategy=%7B%22taskId%22%3A349%2C%22abCheckTime%22%3A1744940145780%2C%22version%22%3A%22exp11%22%2C%22blog-threeH-dialog-exp11tipShowTimes%22%3A5%7D; SESSION=625c14cf-493a-477b-b71f-1ce66f0f8e0c; UserName=sinat_26229211; UserInfo=91516a9cdd71490180241a73e2dc7ff4; UserToken=91516a9cdd71490180241a73e2dc7ff4; UserNick=sinat_26229211; AU=099; UN=sinat_26229211; BT=1745132599775; p_uid=U010000; c_ab_test=1; csdn_newcert_sinat_26229211=1; c_first_ref=default; ssxmod_itna=QuDtjD7bY5BKGHD8D2DEtoAKGQqH4G=tq8biqQHDlrExxA5D8D6DQeGTinb3iCoBAorx5LKtBvIio8orbThQk=7238WfAgfKqAGDAoDhx7QDox0=DnxAQDjxEDeDxhq0rD74irDDxD3uxDCxSKkD04scpHsG2I8+gKsDYPkAxDOjxGC84Gtot7hlxKPY4iaAx0CxRKODmKDIc3kFR5DFEof640kAxi3L7vUS40OhIKODBRs4bYkZ/weL02oolwCkr2DWWDqi=iYvib4WebxIqZTtmrPF7rcUqDWzZUDD; ssxmod_itna2=QuDtjD7bY5BKGHD8D2DEtoAKGQqH4G=tq8biqQD6EK3P40vuQ037WnU2P8nCBW+Zw9Dk8G22hNkoGrhw=887DqidD6r68rC82iLD=obj+ZBa8oja03WcvOe=7OAD17aE1LPaNVfe8f4357Mfzf40m8dUf+MERWqr03LYoc8Af42I7ejRlUTiDL3QQ8TuLD+T3fj5t8SXDcm4Rili3Yac08nKiaffz3ZyDxFc3EiX15pHS4m4+dTyh4zcIVjQCQCTl8K0Gh3TkAiPDKLoDFqD2biD; tfstk=gEjn0E4thCGfz91x91-QowrPd_U9dvtWC_nJw3dz7CR_F3KdvNAlUs8JzTeBU1XPtUeBwkTZ7Lv-LL8e81xlEtWdv_eCsLfA3J6dwBCMbK9j4Q8eaCow9H85JQdpZ3X5iRFYDoBCd3tUMSEY7qr9J3Oz23z9bQ29HzPYDoBE7Jui_SI8Hd89gL-yLU-zbRvy33oyT_Rw7KJxT3-PaRYweLHEzLoE7FR6U3RPa3yGQUDr8IIPuGP1qeJlqOS1jpYHgO4j40b-DeAVLCmzgGvnaIWes0oJidOGTT5zZ0KVl1jkusEofHBc7hJhS8uwTEbF9d1umDRFj9Se9MPtvBSCQZIR_8oyZN72oZWU6VvG79IMWiPmqe_NOZTl25EXvZBAVESUxjO9lLfDYNVZxsSrsVuq5_iWQ8IZP4TeCdAv_rPs__mug_ygIqBW8d9XMgeiSwhj40ozIR0ATeJ6hIC..; _clck=1d5h9ye%7C2%7Cfvd%7C0%7C1934; __gads=ID=ec68afff22ece88c:T=1744948582:RT=1745545171:S=ALNI_MZDL4luoLWK4uVDbi97OSSv62TnFA; __gpi=UID=000010a2e5f16cea:T=1744948582:RT=1745545171:S=ALNI_MZ8n82kL8lCycD3h7St4TWPmLZiJw; __eoi=ID=afe650a6c846ed17:T=1744948582:RT=1745545171:S=AA-AfjZHnALXuL2AYCMFzbDeZ92I; FCNEC=%5B%5B%22AKsRol_zoQqZt9JcXNBTlHJFGE9BX4dfO7t16arQkDmOmgDFp-hG-6NitfLRwW1CsdJukvr5sIfsQ-Lg6GKdxtRVTet5r8YAMwVRrdN73oZjXSVp60hsoFGTGomF-ZLbXNl2hi2Y8Rcl-VcKB4Kk7XCwJLMCxJXcbg%3D%3D%22%5D%5D; c_first_page=https%3A//editor.csdn.net/md/%3Fnot_checkout%3D1%26articleId%3D147295719; dc_session_id=10_1746518721604.276806; c_page_id=default; c_dsid=11_1746519789717.794247; creativeSetApiNew=%7B%22toolbarImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20230921102607.png%22%2C%22publishSuccessImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20240229024608.png%22%2C%22articleNum%22%3A108%2C%22type%22%3A2%2C%22oldUser%22%3Atrue%2C%22useSeven%22%3Afalse%2C%22oldFullVersion%22%3Atrue%2C%22userName%22%3A%22sinat_26229211%22%7D; creative_btn_mp=3; c_pref=https%3A//editor.csdn.net/; c_ref=https%3A//mpbeta.csdn.net/; log_Id_pv=6; Hm_lpvt_6bcd52f51e9b3dce32bec4a3997715ac=1746519978; log_Id_view=202; dc_tos=svtzg0; log_Id_click=4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

  mcp-server-weixin-app:
    #    image: fuzhengwei/  mcp-server-weixin-app:1.1
    image: registry.cn-hangzhou.aliyuncs.com/qx-images/mcp-server-weixin-app:1.0
    container_name: mcp-server-weixin-app
    restart: always
    ports:
      - "8102:8102"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=8102
      - WEIXIN_API_ORIGINAL_ID=gh_dd05c099d67d
      - WEIXIN_API_APP_ID=wxfa86ef6d54566d89
      - WEIXIN_API_APP_SECRET=281fce61c777138f98db0ada779be278
      - WEIXIN_API_TEMPLATE_ID=7UU44yCu2cnWazCYTAohyVS7Dl5L7ezfsP4W
      - WEIXIN_API_TOUSER=oRV6_s2ARRQg27SfGJYs9-hEHDZM
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
