version: '3.8'
# docker-compose -f docker-compose-app-v1.0.yml up -d
services:
  ai-mcp-knowledge-app:
    image: registry.cn-hangzhou.aliyuncs.com/qx-images/ai-mcp-knowledge-app:1.1
    #image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/ai-mcp-knowledge-app:1.0
    container_name: ai-mcp-knowledge-app
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./log:/data/log
      - ./mcp/config:/mcp/config
      - ./mcp/jar:/mcp/jar
    environment:
      - TZ=PRC
      - SERVER_PORT=8090
      - SPRING_AI_OLLAMA_BASE_URL=http://58a39caa684c41bf9bed-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      - SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_NUM_BATCH=512
      - SPRING_AI_OLLAMA_MODEL=nomic-embed-text
      - SPRING_AI_OPENAI_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode
      - SPRING_AI_OPENAI_API_KEY=sk-87d49e5a3e2946288df86c0466613e0c
      - SPRING_AI_MCP_CLIENT_STDIO_SERVERS_CONFIGURATION=file:/mcp/config/mcp-servers-config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
